/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoletaProductsRouteImport } from './routes/loleta-products'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as BrandsIndexRouteImport } from './routes/brands/index'
import { Route as BrandsBrandIdRouteImport } from './routes/brands/$brandId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoletaProductsRoute = LoletaProductsRouteImport.update({
  id: '/loleta-products',
  path: '/loleta-products',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdRoute = BrandsBrandIdRouteImport.update({
  id: '/brands/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRoute
  '/contact': typeof ContactRoute
  '/loleta-products': typeof LoletaProductsRoute
  '/offers': typeof OffersRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/brands/': typeof BrandsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRoute
  '/contact': typeof ContactRoute
  '/loleta-products': typeof LoletaProductsRoute
  '/offers': typeof OffersRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/brands': typeof BrandsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRoute
  '/contact': typeof ContactRoute
  '/loleta-products': typeof LoletaProductsRoute
  '/offers': typeof OffersRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/brands/': typeof BrandsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/branches'
    | '/contact'
    | '/loleta-products'
    | '/offers'
    | '/brands/$brandId'
    | '/brands/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/branches'
    | '/contact'
    | '/loleta-products'
    | '/offers'
    | '/brands/$brandId'
    | '/brands'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/branches'
    | '/contact'
    | '/loleta-products'
    | '/offers'
    | '/brands/$brandId'
    | '/brands/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BranchesRoute: typeof BranchesRoute
  ContactRoute: typeof ContactRoute
  LoletaProductsRoute: typeof LoletaProductsRoute
  OffersRoute: typeof OffersRoute
  BrandsBrandIdRoute: typeof BrandsBrandIdRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loleta-products': {
      id: '/loleta-products'
      path: '/loleta-products'
      fullPath: '/loleta-products'
      preLoaderRoute: typeof LoletaProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId': {
      id: '/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof BrandsBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BranchesRoute: BranchesRoute,
  ContactRoute: ContactRoute,
  LoletaProductsRoute: LoletaProductsRoute,
  OffersRoute: OffersRoute,
  BrandsBrandIdRoute: BrandsBrandIdRoute,
  BrandsIndexRoute: BrandsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
